name: Run and Commit Scripts

on:
    workflow_dispatch:
    
        
jobs:
    run-scripts:
        runs-on: ubuntu-latest

        env:
            NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
            NOTE_DATABASE_ID: ${{ secrets.NOTE_DATABASE_ID }}
            BLOG_DATABASE_ID: ${{ secrets.BLOG_DATABASE_ID }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

            - name: Run doc.py
              run: python doc.py

            - name: Run blog.py
              run: python blog.py

            - name: Commit and push changes
              run: |
                    git config --global user.name 'github-actions[bot]'
                    git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                    git add .
                    git commit -m 'Run doc.py and blog.py and commit changes'
                    git push
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}